### ISSUE TITLE
auctioneer uses hardcoded metron port

### ISSUE THREAD

**Issue by roxtar** [cloudfoundry-incubator/auctioneer#2]
The auctioneer [hardcodes the metron port to be 3457](https://github.com/cloudfoundry-incubator/auctioneer/blob/master/cmd/auctioneer/main.go#L77)

The metron port can be configured in CloudFoundry to be something other than 3457, so a change to the metron port will break auctioneer metrics.

**Comment by ematpl** [comment]
Hi, @roxtar,

The Diego team will address this across the release in https://www.pivotaltracker.com/story/show/103689460, so I'l close this issue out in favor of that.

Thanks,
Eric
